# Generated by Django 5.0 on 2023-12-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('pays', models.CharField(default='', max_length=1000)),
                ('adresse', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=100)),
                ('type_reference', models.CharField(choices=[('Livre', 'Livre'), ('Article de journal', 'Article de journal'), ('Conférence', 'Conférence')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articleApp.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=100)),
                ('resume', models.TextField(default='')),
                ('texte_integral', models.TextField(default='')),
                ('mots_cles', models.CharField(default='', max_length=1000)),
                ('URL_Pdf', models.URLField(default='')),
                ('auteurs', models.ManyToManyField(to='articleApp.auteur')),
                ('references', models.ManyToManyField(to='articleApp.reference')),
            ],
        ),
    ]
