# Generated by Django 5.0 on 2023-12-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0002_elasticdemo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElasticDemo',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='type_reference',
        ),
        migrations.AddField(
            model_name='article',
            name='traiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='auteur',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='adress',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='mots_cles',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='texte_integral',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reference',
            name='titre',
            field=models.TextField(default=''),
        ),
    ]
