# Generated by Django 5.0 on 2024-01-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0003_delete_elasticdemo_remove_auteur_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='mots_cles',
            new_name='motsCles',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='texte_integral',
            new_name='texteIntegral',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='URL_Pdf',
            new_name='urlPdf',
        ),
        migrations.AddField(
            model_name='article',
            name='dateDePublication',
            field=models.DateField(null=True),
        ),
    ]
