# Generated by Django 5.0 on 2024-01-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0004_rename_mots_cles_article_motscles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='texteIntegral',
        ),
    ]
